apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: node-app
      app: node-app
  template:
    metadata:
        labels:
          com.docker.project: node-app
          app: node-app
    spec:
      containers:
        - name: node-app
          image: node
          command:
            - "/bin/sh"
            - "-c"
            - "cd /app && npm install && node app.js"
          env:
          - name: PORT
            value: "3000"
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: node-app-secret
                key: secret
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: node-app-configmap
                key: message
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: app-files
              mountPath: /app/app.js
              subPath: app.js
            - name: app-files
              mountPath: /app/package.json
              subPath: package.json
      volumes:
      - name: app-files
        configMap:
          name: node-app-configmap