apiVersion: v1
kind: Service
metadata:
  name: node-app-svc-lb
  namespace: node-app
spec:
  ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 3000
  selector:
    com.docker.project: node-app
  type: LoadBalancer
status:
  loadBalancer: {}