apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
  namespace: node-app
  labels:
    app: node-app
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
  - port: 80
    targetPort: 3000